version: '3.4'

services:
  qualichain_mcdss:
    hostname: qualichain_mcdss
    container_name: qualichain_mcdss
    restart: always
    build:
      context: ".."
      dockerfile: config/Dockerfile
    ports:
      - 7070:7070
    networks:
      - config_qmediator


networks:
  config_qmediator:
    external: true
